name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Install JDK from Azul
        java-version: '11'   # Android typically requires JDK 11

    # Step 3: Cache Gradle dependencies (optional but recommended)
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    # Step 4: Build the APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # Step 5: Upload the APK as an artifact (optional, to keep the APK for download)
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
